### ISSUE TITLE
Problem with command line version

### ISSUE THREAD

**Issue by bereth** [The-Orange-Toolbox/BSPReveal#1]
![Image of Command Line](https://i.imgur.com/rj8HU2p.png)
The Compile Pal version also seems to fail.

**Comment by maxdup** [comment]
Thanks for reporting, will look into it

**Comment by maxdup** [comment]
I was able to reproduce and fix this error. A new release has been pushed https://github.com/The-Orange-Toolbox/BSPReveal/releases
